# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Deploy to Cloud Run

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  deploy:
    if: github.repository == 'octo-sts/app'
    uses: ./.github/workflows/.terraform.yaml
    permissions:
      contents: read  # clone the repository contents
      id-token: write # federates with GCP
    with:
      project_id: 'octo-sts'
      workload_identity_provider: 'projects/96355665038/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
      service_account: 'github-identity@octo-sts.iam.gserviceaccount.com'
      working_directory: ./iac
      slack_channel: 'octo-sts-alerts'
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
